CREATE TABLE IF NOT EXISTS ZCA_APPRVR_ATTR (
    FORM_NAME     VARCHAR(30) NOT NULL,
    FORM_VER      CHAR(4)     NOT NULL,
    APPR_STEP     VARCHAR(30) NOT NULL,
    FLDGRP_ID     VARCHAR(30) NOT NULL,
    CHECK_METHOD  VARCHAR(61),
    PRIMARY KEY (FORM_NAME, FORM_VER, APPR_STEP, FLDGRP_ID),

    CONSTRAINT FK_ZCA_APPRVR_ATTR_FORM
        FOREIGN KEY (FORM_NAME, FORM_VER)
        REFERENCES ZCA_FORM (FORM_NAME, FORM_VER),

    CONSTRAINT FK_ZCA_APPRVR_ATTR_APPR_LIST
        FOREIGN KEY (FORM_NAME, FORM_VER, APPR_STEP)
        REFERENCES ZCA_APPRVR_LIST (FORM_NAME, FORM_VER, APPR_STEP)
);
